### ISSUE TITLE
Docker Compose로 구성 자동화

### ISSUE THREAD

**Issue by rookedsysc** [rookedsysc/roky-bank#12]
## Overview

Docker Compose로 구성 자동화

## Todo 

- [x] Postgres 분리
- [x] Postgres Table 자동 생헝
- [x] Docker Image 파일로 빌드 
- [x] Docker Compose 파일로 구성 자동화

## Reference 

- https://rookedsysc.vercel.app/blog/tools/docker#docker-hub
